//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntgeltType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="EntgeltType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Waehrung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Brutto" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="Netto" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="MwSt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntgeltType", propOrder = {
    "waehrung",
    "brutto",
    "netto",
    "mwSt"
})
public class EntgeltType {

    @XmlElement(name = "Waehrung", required = true)
    protected String waehrung;
    @XmlElement(name = "Brutto")
    protected double brutto;
    @XmlElement(name = "Netto")
    protected double netto;
    @XmlElement(name = "MwSt")
    protected double mwSt;

    /**
     * Gets the value of the waehrung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaehrung() {
        return waehrung;
    }

    /**
     * Sets the value of the waehrung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaehrung(String value) {
        this.waehrung = value;
    }

    /**
     * Gets the value of the brutto property.
     * 
     */
    public double getBrutto() {
        return brutto;
    }

    /**
     * Sets the value of the brutto property.
     * 
     */
    public void setBrutto(double value) {
        this.brutto = value;
    }

    /**
     * Gets the value of the netto property.
     * 
     */
    public double getNetto() {
        return netto;
    }

    /**
     * Sets the value of the netto property.
     * 
     */
    public void setNetto(double value) {
        this.netto = value;
    }

    /**
     * Gets the value of the mwSt property.
     * 
     */
    public double getMwSt() {
        return mwSt;
    }

    /**
     * Sets the value of the mwSt property.
     * 
     */
    public void setMwSt(double value) {
        this.mwSt = value;
    }

}
