//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LeistungType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="LeistungType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Nummer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="Art" type="{rechnungen}ArtType"/>
 *         <element name="Preis" type="{rechnungen}PreisType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeistungType", propOrder = {
    "nummer",
    "art",
    "preis"
})
public class LeistungType {

    @XmlElement(name = "Nummer")
    protected int nummer;
    @XmlElement(name = "Art", required = true)
    protected ArtType art;
    @XmlElement(name = "Preis", required = true)
    protected PreisType preis;

    /**
     * Gets the value of the nummer property.
     * 
     */
    public int getNummer() {
        return nummer;
    }

    /**
     * Sets the value of the nummer property.
     * 
     */
    public void setNummer(int value) {
        this.nummer = value;
    }

    /**
     * Gets the value of the art property.
     * 
     * @return
     *     possible object is
     *     {@link ArtType }
     *     
     */
    public ArtType getArt() {
        return art;
    }

    /**
     * Sets the value of the art property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtType }
     *     
     */
    public void setArt(ArtType value) {
        this.art = value;
    }

    /**
     * Gets the value of the preis property.
     * 
     * @return
     *     possible object is
     *     {@link PreisType }
     *     
     */
    public PreisType getPreis() {
        return preis;
    }

    /**
     * Sets the value of the preis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreisType }
     *     
     */
    public void setPreis(PreisType value) {
        this.preis = value;
    }

}
