//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rechnungen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rechnungen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rechnungen }
     * 
     * @return
     *     the new instance of {@link Rechnungen }
     */
    public Rechnungen createRechnungen() {
        return new Rechnungen();
    }

    /**
     * Create an instance of {@link RechnungType }
     * 
     * @return
     *     the new instance of {@link RechnungType }
     */
    public RechnungType createRechnungType() {
        return new RechnungType();
    }

    /**
     * Create an instance of {@link LeistungsempfaengerType }
     * 
     * @return
     *     the new instance of {@link LeistungsempfaengerType }
     */
    public LeistungsempfaengerType createLeistungsempfaengerType() {
        return new LeistungsempfaengerType();
    }

    /**
     * Create an instance of {@link ZahlungsmoeglichkeitenType }
     * 
     * @return
     *     the new instance of {@link ZahlungsmoeglichkeitenType }
     */
    public ZahlungsmoeglichkeitenType createZahlungsmoeglichkeitenType() {
        return new ZahlungsmoeglichkeitenType();
    }

    /**
     * Create an instance of {@link AnschriftType }
     * 
     * @return
     *     the new instance of {@link AnschriftType }
     */
    public AnschriftType createAnschriftType() {
        return new AnschriftType();
    }

    /**
     * Create an instance of {@link PositionenType }
     * 
     * @return
     *     the new instance of {@link PositionenType }
     */
    public PositionenType createPositionenType() {
        return new PositionenType();
    }

    /**
     * Create an instance of {@link LeistungType }
     * 
     * @return
     *     the new instance of {@link LeistungType }
     */
    public LeistungType createLeistungType() {
        return new LeistungType();
    }

    /**
     * Create an instance of {@link PreisType }
     * 
     * @return
     *     the new instance of {@link PreisType }
     */
    public PreisType createPreisType() {
        return new PreisType();
    }

    /**
     * Create an instance of {@link ArtType }
     * 
     * @return
     *     the new instance of {@link ArtType }
     */
    public ArtType createArtType() {
        return new ArtType();
    }

    /**
     * Create an instance of {@link EntgeltType }
     * 
     * @return
     *     the new instance of {@link EntgeltType }
     */
    public EntgeltType createEntgeltType() {
        return new EntgeltType();
    }

}
