//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PreisType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Waehrung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Einzel" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         <element name="Gesamt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="MwSt" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreisType", propOrder = {
    "waehrung",
    "einzel",
    "gesamt",
    "mwSt"
})
public class PreisType {

    @XmlElement(name = "Waehrung", required = true)
    protected String waehrung;
    @XmlElement(name = "Einzel")
    protected Double einzel;
    @XmlElement(name = "Gesamt")
    protected double gesamt;
    @XmlElement(name = "MwSt")
    protected Double mwSt;

    /**
     * Gets the value of the waehrung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaehrung() {
        return waehrung;
    }

    /**
     * Sets the value of the waehrung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaehrung(String value) {
        this.waehrung = value;
    }

    /**
     * Gets the value of the einzel property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEinzel() {
        return einzel;
    }

    /**
     * Sets the value of the einzel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEinzel(Double value) {
        this.einzel = value;
    }

    /**
     * Gets the value of the gesamt property.
     * 
     */
    public double getGesamt() {
        return gesamt;
    }

    /**
     * Sets the value of the gesamt property.
     * 
     */
    public void setGesamt(double value) {
        this.gesamt = value;
    }

    /**
     * Gets the value of the mwSt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMwSt() {
        return mwSt;
    }

    /**
     * Sets the value of the mwSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMwSt(Double value) {
        this.mwSt = value;
    }

}
