//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RechnungType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="RechnungType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Leistungsempfaenger" type="{rechnungen}LeistungsempfaengerType"/>
 *         <element name="Leistungserbringer" type="{rechnungen}LeistungserbringerType"/>
 *         <element name="Steuernummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Austellungsdatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="Rechnungsnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Positionen" type="{rechnungen}PositionenType"/>
 *         <element name="Entgelt" type="{rechnungen}EntgeltType"/>
 *         <element name="Zahlungsmoeglichkeiten" type="{rechnungen}ZahlungsmoeglichkeitenType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RechnungType", propOrder = {
    "leistungsempfaenger",
    "leistungserbringer",
    "steuernummer",
    "austellungsdatum",
    "rechnungsnummer",
    "positionen",
    "entgelt",
    "zahlungsmoeglichkeiten"
})
public class RechnungType {

    @XmlElement(name = "Leistungsempfaenger", required = true)
    protected LeistungsempfaengerType leistungsempfaenger;
    @XmlElement(name = "Leistungserbringer", required = true)
    protected LeistungserbringerType leistungserbringer;
    @XmlElement(name = "Steuernummer", required = true)
    protected String steuernummer;
    @XmlElement(name = "Austellungsdatum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar austellungsdatum;
    @XmlElement(name = "Rechnungsnummer", required = true)
    protected String rechnungsnummer;
    @XmlElement(name = "Positionen", required = true)
    protected PositionenType positionen;
    @XmlElement(name = "Entgelt", required = true)
    protected EntgeltType entgelt;
    @XmlElement(name = "Zahlungsmoeglichkeiten", required = true)
    protected ZahlungsmoeglichkeitenType zahlungsmoeglichkeiten;

    /**
     * Gets the value of the leistungsempfaenger property.
     * 
     * @return
     *     possible object is
     *     {@link LeistungsempfaengerType }
     *     
     */
    public LeistungsempfaengerType getLeistungsempfaenger() {
        return leistungsempfaenger;
    }

    /**
     * Sets the value of the leistungsempfaenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeistungsempfaengerType }
     *     
     */
    public void setLeistungsempfaenger(LeistungsempfaengerType value) {
        this.leistungsempfaenger = value;
    }

    /**
     * Gets the value of the leistungserbringer property.
     * 
     * @return
     *     possible object is
     *     {@link LeistungserbringerType }
     *     
     */
    public LeistungserbringerType getLeistungserbringer() {
        return leistungserbringer;
    }

    /**
     * Sets the value of the leistungserbringer property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeistungserbringerType }
     *     
     */
    public void setLeistungserbringer(LeistungserbringerType value) {
        this.leistungserbringer = value;
    }

    /**
     * Gets the value of the steuernummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSteuernummer() {
        return steuernummer;
    }

    /**
     * Sets the value of the steuernummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSteuernummer(String value) {
        this.steuernummer = value;
    }

    /**
     * Gets the value of the austellungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAustellungsdatum() {
        return austellungsdatum;
    }

    /**
     * Sets the value of the austellungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAustellungsdatum(XMLGregorianCalendar value) {
        this.austellungsdatum = value;
    }

    /**
     * Gets the value of the rechnungsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechnungsnummer() {
        return rechnungsnummer;
    }

    /**
     * Sets the value of the rechnungsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechnungsnummer(String value) {
        this.rechnungsnummer = value;
    }

    /**
     * Gets the value of the positionen property.
     * 
     * @return
     *     possible object is
     *     {@link PositionenType }
     *     
     */
    public PositionenType getPositionen() {
        return positionen;
    }

    /**
     * Sets the value of the positionen property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionenType }
     *     
     */
    public void setPositionen(PositionenType value) {
        this.positionen = value;
    }

    /**
     * Gets the value of the entgelt property.
     * 
     * @return
     *     possible object is
     *     {@link EntgeltType }
     *     
     */
    public EntgeltType getEntgelt() {
        return entgelt;
    }

    /**
     * Sets the value of the entgelt property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntgeltType }
     *     
     */
    public void setEntgelt(EntgeltType value) {
        this.entgelt = value;
    }

    /**
     * Gets the value of the zahlungsmoeglichkeiten property.
     * 
     * @return
     *     possible object is
     *     {@link ZahlungsmoeglichkeitenType }
     *     
     */
    public ZahlungsmoeglichkeitenType getZahlungsmoeglichkeiten() {
        return zahlungsmoeglichkeiten;
    }

    /**
     * Sets the value of the zahlungsmoeglichkeiten property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahlungsmoeglichkeitenType }
     *     
     */
    public void setZahlungsmoeglichkeiten(ZahlungsmoeglichkeitenType value) {
        this.zahlungsmoeglichkeiten = value;
    }

}
