//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rechnungen;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZahlungsmoeglichkeitenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ZahlungsmoeglichkeitenType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all>
 *         <element name="IBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="BIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Kontonr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Bitcoin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="BLZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </all>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZahlungsmoeglichkeitenType", propOrder = {

})
public class ZahlungsmoeglichkeitenType {

    @XmlElement(name = "IBAN")
    protected String iban;
    @XmlElement(name = "BIC")
    protected String bic;
    @XmlElement(name = "Kontonr")
    protected String kontonr;
    @XmlElement(name = "Bitcoin")
    protected String bitcoin;
    @XmlElement(name = "BLZ")
    protected String blz;

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBAN() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBAN(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the kontonr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontonr() {
        return kontonr;
    }

    /**
     * Sets the value of the kontonr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontonr(String value) {
        this.kontonr = value;
    }

    /**
     * Gets the value of the bitcoin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitcoin() {
        return bitcoin;
    }

    /**
     * Sets the value of the bitcoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitcoin(String value) {
        this.bitcoin = value;
    }

    /**
     * Gets the value of the blz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBLZ() {
        return blz;
    }

    /**
     * Sets the value of the blz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBLZ(String value) {
        this.blz = value;
    }

}
